version: '3.7'
services:

  nginx:
    build: ./
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - ./templates:/etc/nginx/templates
    networks:
      - nginx-proxy
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - DOMAIN_NAME=mydomain.com

networks:
  nginx-proxy:
    driver: bridge
