version: '3.7'
services:

  nginx:
    build: ./
    container_name: nginx-reverse-proxy
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - ./templates:/etc/nginx/templates
    networks:
      - nginx-proxy
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
      - DOMAIN_NAME=${DOMAIN_NAME}

networks:
  nginx-proxy:
    name: nginx-proxy
    driver: bridge
